language: java
jdk:
  - oraclejdk8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - chmod +x gradlew

addons:
  artifacts:
    s3_region: "us-east-1"
    paths:
      - $(ls /home/travis/build/samgoldman/GradleTesting/testfx-test*.png | tr "\n" ":")
      - /home/travis/build/samgoldman/GradleTesting/build/reports/**/*
