language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - if branch = master OR branch = development;
    then ./gradlew clean check
    else ./gradlew clean fastTests
    fi

after_script:
  zip -r build_artifacts.zip /home/travis/build/samgoldman/GradleTesting/testfx-test*.png /home/travis/build/samgoldman/GradleTesting/build/reports/*

addons:
  artifacts:
    s3_region: "us-east-1"
    paths:
      - build_artifacts.zip