language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
  include:
    - if: branch = master
      script: ./gradlew clean check
    - if: branch = development
      script: ./gradlew clean check
    - if: branch != master AND branch != development
      script: ./gradlew clean fastTest uiFastTest
env:
  global:
    - secure: "jFta33ehNQfeamwLrs8uiDm3kXJAGnVxBnpDp1E+SylOHuLII6gX4rNOx1GjWNUadOX4JwYYSwkVpDLLX1Bi2/1zCTFQzWHPg1HNPrhXE4n2GS/sK8hFV+oLNyQeKCsLS7R95RctPo8IuxA5KJeH61CGz+evUdQixDbyWEpgMukqyog1YAROOi8+DCZn1owo/oKto3ogxlOCbPmguEZCKBpkuMGSOCd34M/JaTnfDaznt3MKnLVpvChvLg7gJ3lDec3sDFaZDMZiy3SPmuDeCNp87CHhkWt7L8LuIwf3EBybQyBrMH2IeLO7AVIv/+KflgBRTZ72DE7ttsKwLb3bXjuMueU8xDVfX30Kpeqdhohh+i17jJab8wYg2OqN2a1ouerWec5E94q1z9Kz9vhul658CRZvg3/zPHGq4SxZhWiD3SxNJQneGi79pIRzF551PkFeZ0mgOnEzsK7zBe0yBHw5TmKAPSGFprWCYEztWeuS/DZeKg2ljTcz25sw8MWnszqkssbuovHB97tyXM5fH/dZNe/8LC7TXJ2L8JVa2WdnD+hfyNC7yCMaHouX2WVf2FEv7Jk8xW6KZdkrIJcq3wn3b6O/tFWhqB/wSBidEZsKly4CTYfmOy06g4DfES4JjAzDK8GhNap2kO/rstwSjMpZANMRHcHu+ssmIjKYtss="
    - secure: "BLcucjlkuMDkvhZEUt3h1555fOqbcgYOqr6Ugn0g7PPjjDi0P8ebnE4TGQIQxhD8jvqj7LGnQkq3gVjxpqF5zwQWzZ2d4ZiP8P6vFPDjWKURyL2z6ikiidvGqYR5HwoCY45S7d9oyxElnkxUlGqBGPSLMZD7GmrCHZ0cwBgSTmfSJJxeAeu3REi51+oUjCgN4SL17q5gJrMphn/uob3niQo1HpKmHBIGSdtvPX3/Okved4ANSAWnq/dk9m5wbCPpHZ63hRTvYEJ3xeohXQLGX3e99t+f48z8R+MqH22y8qU8tPfxQeoipRzQNu8zEHnRZzF2u07rBI/Z3wf3hkEibRnK3KvyXyjnwO+joz7GdiTz0SDLiyiRDNGD+8x1ixw8k074H6YpVI7XIXweUtePHDzyu+7zoKKPG5hu3Ut/uUKH1HGmNPETT/3nu1NAFOU7+7Kk4IOYYDBiQzYuZvpmkrcpp1vvKj6ej+IIi8I/pW61DvGEth9uNqmeELX8XctgMXVjb3UwyedOuUoldBowKaKr/VQ/0UymeeLwYAo9AhIr4Tmh3OGWbuZm4WLVDqMaDGI/wkboUJW0iyRp8HaAkV65DF1EkqHO5AeRLPwWAn/AVQAUFl46KngfkuGx32f6H359hLPqb3zR1zdxDmPaa+xnCcM4vFCCwBMA/PCWylE="


after_script:
  zip -r build_artifacts.zip /home/travis/build/samgoldman/GradleTesting/testfx-test*.png /home/travis/build/samgoldman/GradleTesting/build/reports/*

  - curl --ftp-create-dirs
    -T build_artifacts.zip
    sftp://${SFTP_USER}:${SFTP_PASSWORD}@ravana.dyn.wpi.edu/public_html/softeng-team-n-build-artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/